// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoAHF8p0KYmgqa1wCldmqLmeefw8Zuy8k',
    appId: '1:937762252964:web:4e954af0d24c9e2ff55e31',
    messagingSenderId: '937762252964',
    projectId: 'wellness-app-d1151',
    authDomain: 'wellness-app-d1151.firebaseapp.com',
    storageBucket: 'wellness-app-d1151.firebasestorage.app',
    measurementId: 'G-J7E3X3CC2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTUFLveZ2o8brE4axlhKtxMU66PvFz--0',
    appId: '1:937762252964:android:8414b803a31b5079f55e31',
    messagingSenderId: '937762252964',
    projectId: 'wellness-app-d1151',
    storageBucket: 'wellness-app-d1151.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5cB7uJHL4MSG6U6AdCP1cleMt-J7VOdE',
    appId: '1:937762252964:ios:db4db8d4059149d5f55e31',
    messagingSenderId: '937762252964',
    projectId: 'wellness-app-d1151',
    storageBucket: 'wellness-app-d1151.firebasestorage.app',
    iosBundleId: 'com.example.wellnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5cB7uJHL4MSG6U6AdCP1cleMt-J7VOdE',
    appId: '1:937762252964:ios:db4db8d4059149d5f55e31',
    messagingSenderId: '937762252964',
    projectId: 'wellness-app-d1151',
    storageBucket: 'wellness-app-d1151.firebasestorage.app',
    iosBundleId: 'com.example.wellnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoAHF8p0KYmgqa1wCldmqLmeefw8Zuy8k',
    appId: '1:937762252964:web:3d6b7a5ddfe1ddc5f55e31',
    messagingSenderId: '937762252964',
    projectId: 'wellness-app-d1151',
    authDomain: 'wellness-app-d1151.firebaseapp.com',
    storageBucket: 'wellness-app-d1151.firebasestorage.app',
    measurementId: 'G-53LT24LTTQ',
  );
}
